//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string id { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string Comment1 { get; set; }
        public string ReplyID { get; set; }
        public string SelectedID { get; set; }
    }
}
